config/routes.rb
TibConcert::Application.routes.draw do

  devise_for :admin, :path_names => { :sign_in => 'login', :sign_out => 'logout'},
                     :controllers => { :sessions => "admin/sessions", :passwords => "admin/passwords" }
  devise_for :fans
  
  namespace :api do
   post  "fan/registration"  => "registrations#create"
   post  "fan/sign_in"  => "sessions#create"
   post  "fan/fb/auth"  => "authprovider#create"
   post  "fan/fb/auth"  => "authprovider#create"
   delete "fan/sign_out" =>"sessions#destroy"
   post  "back_stage/fb/auth"  => "authproviderbackstage#create"
   
  end
 
    root :to => 'dashboards#index'
    namespace :admin do
     get "" => "dashboards#index"
     resources :venue
    end

end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  country    :string(255)
#  city       :string(255)
#  state      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  password   :string(255)
#



class Venue < ActiveRecord::Base
 
  attr_accessible :city, :country, :name, :state,:password,:address,:password_confirmation
  validates_presence_of :city,:country,:name,:state,:address
  validates :password, presence: true,length: { :within => 6..40 }
  validates_confirmation_of :password
  has_many :events
end

app/controllers/admin/venue_controller.rb
class Admin::VenueController <  ApplicationController
def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @venues }
    end
  end

  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venue }
    end
  end


  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venue }
    end
  end

  def edit
    @venue = Venue.find(params[:id])
  end


  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to  admin_venue_path(@venue), notice: 'Venue was successfully created.' }
        format.json { render json: @venue, status: :created, location: @venue }
      else
        format.html { render action: "new" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to admin_venue_index_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/venue/_form.html.erb
<body style="margin-left: 93px;">
<%= form_for(@venue,:url=>'/admin/venue') do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
   <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  </div>
   <div class="field">
    <%= f.label :password_conformation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
   <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/venue/edit.html.erb
<h1>Editing venue</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_venue_path(@venue) %> |
<%= link_to 'Back',  admin_venue_index_path %>

app/views/admin/venue/index.html.erb
<h1>Listing venues</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>City</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @venues.each do |venue| %>
  <tr>
    <td><%= venue.name %></td>
    <td><%= venue.country %></td>
    <td><%= venue.city %></td>
    <td><%= venue.state %></td>
    <td><%= link_to 'Show',  admin_venue_path(venue) %></td>
    <td><%= link_to 'Edit',  edit_admin_venue_path(venue) %></td>
    <td><%= link_to 'Destroy',admin_venue_path(venue), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Venue', new_admin_venue_path %>

app/views/admin/venue/new.html.erb
<h1>New venue</h1>

<%= render 'form' %>

<%= link_to 'Back',  admin_venue_index_path %>

app/views/admin/venue/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @venue.name %>
</p>

<p>
  <b>Country:</b>
  <%= @venue.country %>
</p>

<p>
  <b>City:</b>
  <%= @venue.city %>
</p>

<p>
  <b>State:</b>
  <%= @venue.state %>
</p>


<%= link_to 'Edit',  edit_admin_venue_path(@venue) %> |
<%= link_to 'Back', admin_venue_index_url%>